export const Colors = {
  primary: '#E8401C',
  primaryLight: '#FF6B47',
  primaryMuted: '#FDE8E3',
  background: '#F5F3EE',
  surface: '#FFFFFF',
  surfaceWarm: '#FAFAF7',
  text: '#1A1A1A',
  textSecondary: '#6B6B6B',
  textMuted: '#ABABAB',
  border: '#EBEBEB',
  streak: '#E8401C',
  dayActive: '#E8401C',
  dayInactive: '#D4D4D4',
  tabActive: '#E8401C',
  tabInactive: '#ABABAB',
  shadow: 'rgba(0,0,0,0.06)',
  avatarBg: '#F5D5CF',
  avatarText: '#E8401C',
};